CREATE TABLE IF NOT EXISTS motoristas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    cpf TEXT NOT NULL UNIQUE,
    placaVeiculo TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ATIVO' CHECK(status IN ('ATIVO', 'INATIVO'))
;)

CREATE TABLE IF NOT EXISTS entregas (
id INTEGER PRIMARY KEY AUTOINCREMENT,
descricao TEXT NOT NULL,
origem TEXT NOT NULL,
destino TEXT NOT NULL,
status TEXT NOT NULL DEFAULT 'CRIADA' CHECK(status IN ('CRIADA', 'EM_TRANSITO', 'ENTREGUE', 'CANCELADA')),
fk_id_motorista INTEGER REFERENCES motoristas(id)
);

CREATE TABLE IF NOT EXISTS eventos_entrega (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    informacoes TEXT NOT NULL,
    data DATETIME DEFAULT CURRENT_TIMESTAMP,
    fk_id_entrega INTEGER REFERENCES entregas(id) ON DELETE CASCADE
);